### ISSUE TITLE
Cepstral Mean Normaliztion in Feature Extraction does not work/

### ISSUE THREAD

**Issue by ben-kraus** [Sciss/SpeechRecognitionHMM#2]
It is calculated and stored in mCeps[][] in the FeatureExtract Class but never writen back in mfccFeature[][], so it will never be used i guess.

**Comment by Sciss** [comment]
Thank you for reporting. I am not actively working on this project, so if you can create a related pull request, I could review and eventually merge that.

**Comment by Sciss** [comment]
you might want to raise that issue here: https://github.com/gtiwari333/speech-recognition-java-hidden-markov-model-vq-mfcc
